version: '3.4'

services:
  dsservicesgateway:
    image: morthall/dsservicesgateway
    build:
      context: .
      dockerfile: DSServicesGateway/Dockerfile
    depends_on:
      - numbergamesprovider
      - subscriptionservices
      - funservice

  numbergamesprovider:
    image: morthall/numbergamesprovider
    build:
      context: .
      dockerfile: NumberGamesProvider/Dockerfile

  subscriptionservices:
    image: morthall/subscriptionservices
    build:
      context: .
      dockerfile: SubscriptionServices/Dockerfile


  funservice:
    image: morthall/funservice
    build:
      context: .
      dockerfile: FunService/Dockerfile
  
  redisService: 
    image: redis:5.0

  